package com.partlinq.core.model.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Invoice data record for generating invoices/receipts.
 * Contains all data needed to render an invoice in any format (PDF, HTML, WhatsApp text).
 *
 * Ground reality: Technician picks parts, gets a parchi (receipt).
 * This digitizes the parchi. Can be sent via WhatsApp or printed.
 */
public record InvoiceData(
	// Invoice metadata
	String invoiceNumber,
	LocalDateTime invoiceDate,
	String orderNumber,
	UUID orderId,

	// Shop details (seller)
	String shopName,
	String shopAddress,
	String shopCity,
	String shopPhone,
	String shopGstNumber,

	// Technician details (buyer)
	String technicianName,
	String technicianPhone,
	String technicianCity,

	// Line items
	List<InvoiceLineItem> items,

	// Totals
	BigDecimal subtotal,
	BigDecimal gstAmount,
	BigDecimal totalAmount,

	// Payment info
	boolean isPaidOnCredit,
	BigDecimal currentOutstandingBalance,
	LocalDateTime paymentDueDate,

	// Footer
	String notes
) {
	/**
	 * Individual line item on the invoice.
	 */
	public record InvoiceLineItem(
		int serialNumber,
		String partNumber,
		String partName,
		String brand,
		int quantity,
		BigDecimal unitPrice,
		BigDecimal lineTotal
	) {}

	/**
	 * Generate a WhatsApp-friendly text version of this invoice.
	 * This is the most-used format — shop owners send it via WhatsApp.
	 */
	public String toWhatsAppText() {
		StringBuilder sb = new StringBuilder();
		sb.append("*").append(shopName).append("*\n");
		sb.append(shopAddress).append(", ").append(shopCity).append("\n");
		sb.append("Ph: ").append(shopPhone).append("\n");
		if (shopGstNumber != null && !shopGstNumber.isEmpty()) {
			sb.append("GST: ").append(shopGstNumber).append("\n");
		}
		sb.append("─────────────────\n");
		sb.append("*Invoice #").append(invoiceNumber).append("*\n");
		sb.append("Date: ").append(invoiceDate.toLocalDate()).append("\n");
		sb.append("Order: ").append(orderNumber).append("\n");
		sb.append("─────────────────\n");
		sb.append("*To:* ").append(technicianName).append("\n");
		sb.append("Ph: ").append(technicianPhone).append("\n");
		sb.append("─────────────────\n");

		for (InvoiceLineItem item : items) {
			sb.append(item.serialNumber()).append(". ");
			sb.append(item.partName());
			if (item.brand() != null) {
				sb.append(" (").append(item.brand()).append(")");
			}
			sb.append("\n");
			sb.append("   ").append(item.quantity()).append(" x ₹").append(item.unitPrice().toPlainString());
			sb.append(" = ₹").append(item.lineTotal().toPlainString()).append("\n");
		}

		sb.append("─────────────────\n");
		sb.append("*Total: ₹").append(totalAmount.toPlainString()).append("*\n");

		if (isPaidOnCredit) {
			sb.append("\n_Paid on credit (udhaar)_\n");
			if (currentOutstandingBalance != null) {
				sb.append("Outstanding balance: ₹").append(currentOutstandingBalance.toPlainString()).append("\n");
			}
			if (paymentDueDate != null) {
				sb.append("Due by: ").append(paymentDueDate.toLocalDate()).append("\n");
			}
		} else {
			sb.append("\n_Paid_\n");
		}

		if (notes != null && !notes.isEmpty()) {
			sb.append("\nNote: ").append(notes).append("\n");
		}

		sb.append("\n_Generated by PartLinQ_");
		return sb.toString();
	}
}
