package com.partlinq.core.model.entity;

import com.partlinq.core.model.enums.NotificationType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Notification entity — stores all notifications generated by the system.
 * Designed to be channel-agnostic: WhatsApp, SMS, push, or in-app.
 *
 * Current reality: Most notifications will be sent via WhatsApp (using WhatsApp Business API).
 * SMS as fallback. In-app for future mobile app.
 */
@Entity
@Table(name = "notifications", indexes = {
	@Index(name = "idx_notif_recipient_read", columnList = "recipient_phone,is_read"),
	@Index(name = "idx_notif_type_sent", columnList = "notification_type,is_sent")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString(exclude = {"technician", "shop"})
public class Notification {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	@EqualsAndHashCode.Include
	private UUID id;

	/**
	 * Type of notification
	 */
	@Column(name = "notification_type", nullable = false)
	@Enumerated(EnumType.STRING)
	private NotificationType notificationType;

	/**
	 * Phone number of the recipient (primary delivery channel)
	 */
	@Column(name = "recipient_phone", nullable = false, length = 20)
	private String recipientPhone;

	/**
	 * Name of the recipient (for personalization)
	 */
	@Column(nullable = false, length = 255)
	private String recipientName;

	/**
	 * Related technician (if applicable)
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "technician_id")
	private Technician technician;

	/**
	 * Related shop (if applicable)
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shop_id")
	private PartsShop shop;

	/**
	 * Short title for the notification
	 */
	@Column(nullable = false, length = 200)
	private String title;

	/**
	 * Full message body (WhatsApp-formatted)
	 */
	@Column(nullable = false, length = 2000)
	private String messageBody;

	/**
	 * Delivery channel used
	 */
	@Column(nullable = false, length = 20)
	@Builder.Default
	private String channel = "WHATSAPP";

	/**
	 * Whether the notification has been sent
	 */
	@Column(name = "is_sent", nullable = false)
	@Builder.Default
	private Boolean isSent = false;

	/**
	 * When the notification was sent
	 */
	@Column
	private LocalDateTime sentAt;

	/**
	 * Whether the notification has been read/acknowledged
	 */
	@Column(name = "is_read", nullable = false)
	@Builder.Default
	private Boolean isRead = false;

	/**
	 * Retry count for failed deliveries
	 */
	@Column(nullable = false)
	@Builder.Default
	private Integer retryCount = 0;

	/**
	 * Error message if delivery failed
	 */
	@Column(length = 500)
	private String errorMessage;

	@CreationTimestamp
	@Column(nullable = false, updatable = false)
	private LocalDateTime createdAt;
}
